/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3135",
        outline: "#727784",
        "inverse-on-surface": "#eef1f6",
        "on-primary": "#ffffff",
        "surface-tint": "#115cb9",
        "on-secondary-container": "#616363",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed": "#001a40",
        "tertiary-fixed": "#e1e3e4",
        "tertiary-container": "#57595a",
        "on-background": "#181c20",
        secondary: "#5d5f5f",
        "primary-fixed-dim": "#acc7ff",
        "on-tertiary-container": "#ced0d1",
        "surface-container-low": "#f1f4f9",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-bright": "#f7f9ff",
        "on-surface": "#181c20",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e8",
        "primary-fixed": "#d7e2ff",
        tertiary: "#3f4243",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "primary-container": "#0056b3",
        "on-primary-fixed-variant": "#004491",
        "surface-container-high": "#e5e8ee",
        "secondary-container": "#dfe0e0",
        "surface-container-lowest": "#ffffff",
        primary: "#003f87",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#454748",
        "inverse-primary": "#acc7ff",
        "on-surface-variant": "#424752",
        "secondary-fixed-dim": "#c6c6c7",
        "on-error-container": "#93000a",
        background: "#f7f9ff",
        "on-tertiary-fixed": "#191c1d",
        "surface-dim": "#d7dadf",
        "outline-variant": "#c2c6d4",
        "on-secondary-fixed-variant": "#454747",
        "surface-container": "#ebeef3",
        "surface-variant": "#e0e3e8",
        surface: "#f7f9ff",
        "on-primary-container": "#bbd0ff",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "80px",
        "stack-sm": "16px",
        "margin-desktop": "64px",
        "stack-md": "32px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        caption: ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
    },
      fontSize: {
        display: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
